#spring.application.name=Fingpay
#spring.datasource.url=jdbc:mysql://localhost:3306/venus_db
#spring.datasource.username=root
#spring.datasource.password=9572Vikas@#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server.port=9090

spring.datasource.url=jdbc:mysql://database-1.cd2eyywiufeo.ap-south-1.rds.amazonaws.com:3306/venus_db
spring.datasource.username=admin
spring.datasource.password=Ajay9102
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://database-1.clikoqku0c3m.ap-south-1.rds.amazonaws.com:3306/venus_db
#spring.datasource.username=admin
#spring.datasource.password=9572Vikas
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

fingpay.base.url=https://fpuat.tapits.in
fingpay.base.url.uat=https://fpuat.tapits.in
fingpay.username=UJJWALPAYd
#fingpay.password=UJJWALPAY@7800
fingpay.password=796c3ee556ac31f3754a38cfd15b8044
fingpay.supermerchant.id=1407
device.imei=352801082418919
fingpay.secret.key=adb9af1d9d8c573d8600d73754c248c9343ce074d68af0722af434bc922061fa
fingpay.public.key.path=classpath:fingpay.cer
fingpay.ip=223.235.103.251
fingpay.onboard.url=https://fingpayap.tapits.in/fpaepsweb/api/onboarding/merchant/creation/v2
#fingpay.onboard.url=https://fpuat.tapits.in/fpaepsweb/api/onboarding/merchant/simple/creation/v2
fingpay.ekyc.url=https://fpekyc.tapits.in/fpekyc/api/ekyc/merchant/sendotp