import DistributorLayout from '../../components/DistributorLayout';
import { Download, CheckCircle2, ShieldCheck, Gift, LifeBuoy, History } from 'lucide-react';

const DistributorInvoices = () => (
    <DistributorLayout>
        <div className="flex flex-col gap-8">
            <div className="flex flex-col gap-1"><h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none leading-none">Your Invoices</h1><p className="text-xs font-black text-slate-400 uppercase tracking-[0.25em] mt-2">Manage billing and network settlements</p></div>
            <div className="bg-white p-10 rounded-[3rem] shadow-sm border border-slate-50"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-slate-50 text-[10px] font-black text-slate-400 uppercase tracking-widest text-left"><th className="py-6">Invoice #</th><th className="py-6">Description</th><th className="py-6">Total Amount</th><th className="py-6">Status</th><th className="py-6">Date</th><th className="py-6 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-50">{[1,2,3].map(i => (<tr key={i} className="group hover:bg-slate-50/50 transition-all"><td className="py-6 text-sm font-black text-[#111e35]">INV-2024-00{i}</td><td className="py-6 text-xs font-bold text-slate-400">Monthly Platform Maintenance Tier {i}</td><td className="py-6 text-sm font-black text-slate-900">₹{i*1250}.00</td><td className="py-6"><span className="flex items-center gap-1.5 px-3 py-1 bg-green-50 text-green-600 rounded-full text-[9px] font-black uppercase tracking-widest w-fit border border-green-100"><CheckCircle2 size={12} strokeWidth={3} /> Paid</span></td><td className="py-6 text-xs font-bold text-slate-400">28 Mar, 2024</td><td className="py-6 text-right"><div className="w-10 h-10 bg-slate-50 rounded-xl flex items-center justify-center text-blue-600 ml-auto cursor-pointer hover:bg-blue-600 hover:text-white transition-all"><Download size={16} /></div></td></tr>))}</tbody></table></div></div>
        </div>
    </DistributorLayout>
);

const DistributorAccounts = () => (
    <DistributorLayout>
        <div className="flex flex-col gap-8"><h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none">Security & Accounts</h1><div className="bg-white p-10 rounded-[3rem] shadow-sm border border-slate-50 flex flex-col gap-10"><div className="flex justify-between items-center"><div className="flex flex-col gap-1"><h3 className="text-xl font-black text-[#111e35] tracking-tight">Financial Linked Identity</h3><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Primary Settlement Account</p></div><div className="flex items-center gap-2 px-3 py-1 bg-green-50 text-green-600 rounded-full text-[9px] font-black uppercase tracking-widest w-fit border border-green-100"><ShieldCheck size={12} strokeWidth={3} /> ACTIVE & VERIFIED</div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ label: 'Full Owner Name', value: 'OM DUBEY' }, { label: 'Settlement Bank', value: 'SBI (X...9845)' }, { label: 'GSTIN Number', value: '09ABCPD4938C1Z4' }, { label: 'Region Hub', value: 'North - New Delhi' }].map((item, i) => (<div key={i} className="flex flex-col gap-2"><span className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{item.label}</span><div className="flex items-center gap-3 p-5 bg-slate-50 rounded-2xl border border-slate-100 shadow-sm"><span className="text-sm font-black text-slate-700">{item.value}</span></div></div>))}</div><button className="w-full py-5 bg-[#111e35] text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl hover:bg-black active:scale-95 transition-all">Update Account Documents</button></div></div>
    </DistributorLayout>
);

const DistributorPromotions = () => (
    <DistributorLayout>
        <div className="flex flex-col gap-8"><h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none leading-none">Promotion Center</h1><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-10">{[{ title: 'Refer & Earn 2%', desc: 'Earn extra comm for every active retailer you bring.', color: 'from-blue-600 to-blue-800' }, { title: 'Festive Mega Bonus', desc: 'Get ₹5k back on crossing ₹10L volume.', color: 'from-rose-500 to-rose-700' }, { title: 'Retailer Of Month', desc: 'Top merchants win cash back or free upgrades.', color: 'from-emerald-500 to-emerald-700' }].map((gift, i) => (<div key={i} className={`p-10 rounded-[3rem] bg-gradient-to-br ${gift.color} text-white shadow-2xl flex flex-col gap-6 relative overflow-hidden group`}><Gift size={40} className="text-white/20 absolute -right-4 -top-4 group-hover:scale-125 transition-all" /><h3 className="text-xl font-black tracking-tight">{gift.title}</h3><p className="text-xs font-bold opacity-80 leading-relaxed uppercase tracking-widest">{gift.desc}</p><button className="w-full py-4 bg-white/10 hover:bg-white/20 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all">Claim Now</button></div>))}</div></div>
    </DistributorLayout>
);

const DistributorSupport = () => (
    <DistributorLayout>
        <div className="flex flex-col gap-8"><h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none leading-none text-left">Elite Support Center</h1><div className="flex flex-col xl:flex-row gap-8"><div className="flex-1 bg-white p-10 rounded-[3rem] shadow-sm border border-slate-50 flex flex-col gap-8"><h3 className="text-xl font-black text-[#111e35] tracking-tight">Contact Dedicated Manager</h3><p className="text-xs font-bold text-slate-400 leading-relaxed uppercase tracking-widest">Connect directly with your distributor Relationship Manager for high-volume support.</p><div className="space-y-4">{[{ label: 'Direct Phone', value: '+91 91234 56780', color: 'text-blue-500' }, { label: 'Email Support', value: 'rm-support@ujjwalpay.com', color: 'text-amber-500' }, { label: 'Priority WhatsApp', value: 'Live Hub Access', color: 'text-emerald-500' }].map((c, i) => (<div key={i} className="flex justify-between items-center p-6 bg-slate-50 rounded-2xl border border-slate-100 group hover:border-[#ffb400] transition-all"><span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{c.label}</span><span className={`text-sm font-black ${c.color}`}>{c.value}</span></div>))}</div><button className="w-full py-5 bg-[#ffb400] text-white rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-yellow-500/10">Launch Chat Hub</button></div><div className="w-full xl:w-[400px] flex flex-col gap-8"><div className="bg-[#111e35] p-10 rounded-[3rem] text-white flex flex-col gap-6 shadow-2xl relative overflow-hidden"><LifeBuoy size={100} className="text-white/5 absolute -right-10 -top-10" fill="white" /><h3 className="text-xl font-black tracking-tight relative z-10">Instant Help</h3><p className="text-xs font-bold text-slate-400 leading-relaxed uppercase tracking-widest relative z-10">Access the knowledge base for immediate operational issues.</p><button className="py-4 bg-white/10 hover:bg-white/20 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all relative z-10">Access Documents</button></div></div></div></div>
    </DistributorLayout>
);

const DistributorOldReports = () => (
    <DistributorLayout>
        <div className="flex flex-col gap-8"><h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none leading-none">Financial History Archive</h1><div className="bg-white p-10 rounded-[3rem] shadow-sm border border-slate-50 flex flex-col gap-8"><div className="flex justify-between items-center"><h3 className="text-xl font-black text-[#111e35] tracking-tight">Settled Fiscal Years</h3><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none">Access historical network data for previous FYs.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">{['FY 2022-2023', 'FY 2021-2022', 'FY 2020-2021'].map(fy => (<div key={fy} className="flex justify-between items-center p-8 bg-slate-50 rounded-[2rem] border border-slate-100 group hover:border-[#111e35] transition-all"><div className="flex items-center gap-6"><div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-slate-300 group-hover:bg-[#111e35] group-hover:text-white transition-all shadow-sm"><History size={20} /></div><span className="text-sm font-black text-slate-700">{fy}</span></div><div className="p-3 bg-white rounded-xl text-blue-600 hover:bg-blue-600 hover:text-white transition-all shadow-sm cursor-pointer"><Download size={18} /></div></div>))}</div></div></div>
    </DistributorLayout>
);

export { DistributorInvoices, DistributorAccounts, DistributorPromotions, DistributorSupport, DistributorOldReports };
